config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/stats', to: 'statistics#index'

  resources :items, only: %i[index show]
  resources :logs, only: %i[create destroy]
  # POST /logsの後のreloadを想定
  get '/logs', to: 'users#home'

  authenticated :user do
    root 'users#home', as: :authenticated_root
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  get '/users', to: 'users#registrations'
  get '/about', to: 'static_pages#about'
  get '/privacy_policy', to: 'static_pages#privacy'
  get '/terms_of_service', to: 'static_pages#service'
  root 'static_pages#home'
  post '/guest', to: 'users#guest'

  namespace :api do
    resources :items, only: %i[index update]
    namespace :stats do
      get 'all_lines'
      get 'all_pies'
      get 'accumulate_amounts'
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home; end

  def about; end

  def privacy; end

  def service; end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<section>
  <h2 class="border-bottom border-secondary pb-3" style="--bs-border-opacity: .75;">このアプリでできること</h2>
  <p>資格の勉強や習いごと、ついついみちゃったYoutubeなど自分自身の活動を項目に分けて15分単位で記録できます。</p>
  <p>記録した内容を項目別の時間数や、期間別の割合で見ることができます。</p>
</section>
<section>
  <h2 class="border-bottom border-secondary pb-3" style="--bs-border-opacity: .75;">アプリの使い方</h2>
  <h5 class="my-5">入力画面で、時間を設定した項目を入力する</h5>
  <%= image_pack_tag 'media/images/log_form.png', alt: "入力画面のスクリーンショット", class: "border border-2 img-fluid" %>
  <h5 class="my-5">記録する活動を自分で設定できます。</h5>
  <%= image_pack_tag 'media/images/item_index.png', alt: "項目名の編集画面", class: "border border-2 img-fluid" %>
  <h5 class="my-5">統計ページで記録したデータを見ることができます。</h5>
  <%= image_pack_tag 'media/images/stats.png', alt: "入力画面のスクリーンショット", class: "border border-2 img-fluid" %>
</section>
<section>
  <h5 class="border-bottom border-secondary pb-3 my-5" style="--bs-border-opacity: .75;">サイト名の由来</h5>
  <p>recordaは、ポルトガル語で'~を覚える'という意味です。英語で言うrememberに近い意味を持ちます。
    <br />
    自分をrecord(記録)するだけでなく、アプリにremember(記憶)してもらうことで、自身を客観的にみる一歩を手助けできればという思いがあります。
  </p>
</section>

app/views/static_pages/home.html.erb
<section class="container">
  <div class="row py-lg-w5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">Recorda me<br>自分自身を記録しよう</h1>
      <p class="lead text-muted">自分の活動を記録し、可視化する</p>
      <p class="lead text-muted pb-1">
        やらなきゃいけないことがあるのに、<br />
        うまく継続できない...<br />
      Recorda meはそんな人のためのアプリです<br />
      <br />
        時間を家計簿のように記録してみましょう
      </p>
      <div class="d-grid gap-2 col-6 mx-auto">
        <%= link_to "新規登録", new_user_registration_path, class: "btn btn-secondary"%>
        <%= link_to "ログイン", new_user_session_path, class: "btn btn-outline-secondary"%>
        <%= link_to "ゲストとしてアプリを試す", guest_path, method: :post %>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/privacy.html.erb
<div class="container">
  <h2 class="p-3">プライバシーポリシー</h2>
  <p class="text-start">
    このサイトの運営者（以下、「当人」といいます。）は、本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）における、ユーザーの個人情報の取扱いについて、以下のとおりプライバシーポリシー（以下、「本ポリシー」といいます。）を定めます。
  </p>

  <h4 class="p-3">第1条（個人情報）</h4>
  <p class="text-start">
    「個人情報」とは、個人情報保護法にいう「個人情報」を指すものとし、生存する個人に関する情報であって、当該情報に含まれる氏名、生年月日、住所、電話番号、連絡先その他の記述等により特定の個人を識別できる情報及び容貌、指紋、声紋にかかるデータ、及び健康保険証の保険者番号などの当該情報単体から特定の個人を識別できる情報（個人識別情報）を指します。
  </p>

  <h4 class="p-3">第2条（個人情報の収集方法）</h4>
  <p class="text-start">
    当人は、ユーザーが利用登録をする際に氏名、生年月日、住所、電話番号、メールアドレスなどの個人情報をお尋ねすることがあります。また、ユーザーと提携先などとの間でなされたユーザーの個人情報を含む取引記録や決済に関する情報を,当人の提携先（情報提供元、広告主、広告配信先などを含みます。以下、｢提携先｣といいます。）などから収集することがあります。
  </p>

  <h4 class="p-3">第3条（個人情報を収集・利用する目的）</h4>
  <p class="text-start">
    当人が個人情報を収集・利用する目的は、以下のとおりです。
  <ol class='text-start'>
    <li>当人サービスの提供・運営のため</li>
    <li>ユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）</li>
    <li>ユーザーが利用中のサービスの新機能、更新情報、キャンペーン等及び当人が提供する他のサービスの案内のメールを送付するため</li>
    <li>メンテナンス、重要なお知らせなど必要に応じたご連絡のため</li>
    <li>利用規約に違反したユーザーや、不正・不当な目的でサービスを利用しようとするユーザーの特定をし、ご利用をお断りするため</li>
    <li>ユーザーにご自身の登録情報の閲覧や変更、削除、ご利用状況の閲覧を行っていただくため</li>
    <li>上記の利用目的に付随する目的</li>
  </ol>
  </p>

  <h4 class="p-3">第4条（利用目的の変更）</h4>
  <p class="text-start">
    当人は、利用目的が変更前と関連性を有すると合理的に認められる場合に限り、個人情報の利用目的を変更するものとします。
    利用目的の変更を行った場合には、変更後の目的について、当人所定の方法により、ユーザーに通知し、または本ウェブサイト上に公表するものとします。
  </p>

  <h4 class="p-3">第5条（個人情報の第三者提供）</h4>
  <p class="text-start">
  <ol class="text-start">
    <li class="pb-2">当人は、次に掲げる場合を除いて、あらかじめユーザーの同意を得ることなく、第三者に個人情報を提供することはありません。ただし、個人情報保護法その他の法令で認められる場合を除きます。</li>
    <ol class="text-start">
      <li>人の生命、身体または財産の保護のために必要がある場合であって、本人の同意を得ることが困難であるとき</li>
      <li>公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって、本人の同意を得ることが困難であるとき</li>
      <li>国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって、本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき</li>
      <li class="pb-2">予め次の事項を告知あるいは公表し、かつ当人が個人情報保護委員会に届出をしたとき</li>
      <ol class="text-start">
        <li>利用目的に第三者への提供を含むこと</li>
        <li>第三者に提供されるデータの項目</li>
        <li>第三者への提供の手段または方法</li>
        <li>本人の求めに応じて個人情報の第三者への提供を停止すること</li>
        <li class="pb-2">本人の求めを受け付ける方法</li>
      </ol>
    </ol>
    <li class="pb-2">前項の定めにかかわらず、次に掲げる場合には、当該情報の提供先は第三者に該当しないものとします。</li>
    <ol class="text-start">
      <li>当人が利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合</li>
      <li>合併その他の事由による事業の承継に伴って個人情報が提供される場合</li>
      <li>合併その他の事由による事業の承継に伴って個人情報が提供される場合</li>
    </ol>
  </ol>
  </p>

  <h4 class="p-3">第6条（個人情報の開示）</h4>
  <p class="text-start">
  <ol class="text-start">
    <li class="pb-2">
      当人は、本人から個人情報の開示を求められたときは、本人に対し、遅滞なくこれを開示します。ただし、開示することにより次のいずれかに該当する場合は、その全部または一部を開示しないこともあり、開示しない決定をした場合には、その旨を遅滞なく通知します。なお、個人情報の開示に際しては、1件あたり1、000円の手数料を申し受けます。
    </li>
    <ol class="text-start">
      <li>本人または第三者の生命、身体、財産その他の権利利益を害するおそれがある場合</li>
      <li>当人の業務の適正な実施に著しい支障を及ぼすおそれがある場合</li>
      <li class="pb-2">その他法令に違反することとなる場合</li>
    </ol>
    <li>前項の定めにかかわらず、履歴情報および特性情報などの個人情報以外の情報については、原則として開示いたしません。</li>
  </ol>
  </p>

  <h4 class="p-3">第7条（個人情報の訂正および削除）</h4>
  <ol class="text-start">
    <li>ユーザーは、当人の保有する自己の個人情報が誤った情報である場合には、当人が定める手続きにより、当人に対して個人情報の訂正、追加または削除（以下、「訂正等」といいます。）を請求することができます。</li>
    <li>当人は、ユーザーから前項の請求を受けてその請求に応じる必要があると判断した場合には、遅滞なく、当該個人情報の訂正等を行うものとします。</li>
    <li>当人は、前項の規定に基づき訂正等を行った場合、または訂正等を行わない旨の決定をしたときは遅滞なく、これをユーザーに通知します。</li>
  </ol>

  <h4 class="p-3">第8条（個人情報の利用停止等）</h4>
  <ol class="text-start">
    <li>
      当人は、本人から個人情報が利用目的の範囲を超えて取り扱われているという理由、または不正の手段により取得されたものであるという理由により、その利用の停止または消去（以下、「利用停止等」といいます。）を求められた場合には、遅滞なく必要な調査を行います。
    </li>
    <li>前項の調査結果に基づき、その請求に応じる必要があると判断した場合には、遅滞なく、当該個人情報の利用停止等を行います。</li>
    <li>当人は、前項の規定に基づき利用停止等を行った場合、または利用停止等を行わない旨の決定をしたときは、遅滞なく、これをユーザーに通知します。</li>
    <li>前2項にかかわらず、利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって、ユーザーの権利利益を保護するために必要なこれに代わるべき措置をとれる場合は、この代替策を講じるものとします。</li>
  </ol>

  <h4 class="p-3">第9条（プライバシーポリシーの変更）</h4>
  <ol class="text-start">
    <li>本ポリシーの内容は、法令その他本ポリシーに別段の定めのある事項を除いて、ユーザーに通知することなく、変更することができるものとします。</li>
    <li>当人が別途定める場合を除いて、変更後のプライバシーポリシーは、本ウェブサイトに掲載したときから効力を生じるものとします。</li>
  </ol>

  <h4 class="p-3">第10条（お問い合わせ窓口）</h4>
  <p class="text-start">本ポリシーに関するお問い合わせは、下記の窓口までお願いいたします。</p>
  <p class="text-start">運営者: 高橋
    <br>Eメールアドレス: vol-ume@outlook.jp
  </p>
  <p class="text-end">以上</p>
</div>

app/views/static_pages/service.html.erb
<div class="container">
  <h2 class="p-3">利用規約</h2>
  <p class="text-start">
    この利用規約（以下、「本規約」といいます。）は、運営者（以下、「当人」といいます。）がこのウェブサイト上で提供するサービス（以下、「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下、「ユーザー」といいます。）には、本規約に従って、本サービスをご利用いただきます。
  </p>

  <h4 class="p-3">第1条（適用）</h4>
  <ol class="text-start">
    <li>本規約は、ユーザーと当人との間の本サービスの利用に関わる一切の関係に適用されるものとします。</li>
    <li>当人は本サービスに関し、本規約のほか、ご利用にあたってのルール等、各種の定め（以下、「個別規定」といいます。）をすることがあります。これら個別規定はその名称のいかんに関わらず、本規約の一部を構成するものとします。</li>
    <li>本規約の規定が前条の個別規定の規定と矛盾する場合には、個別規定において特段の定めなき限り、個別規定の規定が優先されるものとします。</li>
  </ol>

  <h4 class="p-3">第2条（利用登録）</h4>
  <ol class="text-start">
    <li>本サービスにおいては、登録希望者が本規約に同意の上、当人の定める方法によって利用登録を申請し、当人がこれを承認することによって、利用登録が完了するものとします。</li>
    <li>当人は、利用登録の申請者に以下の事由があると判断した場合、利用登録の申請を承認しないことがあり、その理由については一切の開示義務を負わないものとします。
      <ol class="text-start py-2">
        <li>利用登録の申請に際して虚偽の事項を届け出た場合</li>
        <li>本規約に違反したことがある者からの申請である場合</li>
        <li>その他、当人が利用登録を相当でないと判断した場合</li>
      </ol>
    </li>
  </ol>

  <h4 class="p-3">第3条（ユーザーIDおよびパスワードの管理）</h4>
  <ol class="text-start">
    <li>ユーザーは、自己の責任において、本サービスのユーザーIDおよびパスワードを適切に管理するものとします。</li>
    <li>
      ユーザーは、いかなる場合にも、ユーザーIDおよびパスワードを第三者に譲渡または貸与し、もしくは第三者と共用することはできません。当人は、ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には、そのユーザーIDを登録しているユーザー自身による利用とみなします。
    </li>
    <li>ユーザーID及びパスワードが第三者によって使用されたことによって生じた損害は、当人に故意又は重大な過失がある場合を除き、当人は一切の責任を負わないものとします。</li>
  </ol>
  
  <h4 class="p-3">第5条（禁止事項）</h4>
  <p class="text-start">ユーザーは、本サービスの利用にあたり、以下の行為をしてはなりません。</p>

  <ol class="text-start">
    <li>法令または公序良俗に違反する行為</li>
    <li>犯罪行為に関連する行為</li>
    <li>本サービスの内容等、本サービスに含まれる著作権、商標権ほか知的財産権を侵害する行為</li>
    <li>当人、ほかのユーザー、またはその他第三者のサーバーまたはネットワークの機能を破壊したり、妨害したりする行為</li>
    <li>本サービスによって得られた情報を商業的に利用する行為</li>
    <li>当人のサービスの運営を妨害するおそれのある行為</li>
    <li>不正アクセスをし、またはこれを試みる行為</li>
    <li>他のユーザーに関する個人情報等を収集または蓄積する行為</li>
    <li>不正な目的を持って本サービスを利用する行為</li>
    <li>本サービスの他のユーザーまたはその他の第三者に不利益、損害、不快感を与える行為</li>
    <li>他のユーザーに成りすます行為</li>
    <li>当人が許諾しない本サービス上での宣伝、広告、勧誘、または営業行為</li>
    <li>面識のない異性との出会いを目的とした行為</li>
    <li>当人のサービスに関連して、反社会的勢力に対して直接または間接に利益を供与する行為</li>
    <li>その他、当人が不適切と判断する行為</li>
  </ol>

  <h4 class="p-3">第6条（本サービスの提供の停止等）</h4>
  <ol class="text-start">
    <li>当人は、以下のいずれかの事由があると判断した場合、ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。
      <ol class="text-start py-2">
        <li>本サービスにかかるコンピュータシステムの保守点検または更新を行う場合</li>
        <li>地震、落雷、火災、停電または天災などの不可抗力により、本サービスの提供が困難となった場合</li>
        <li>コンピュータまたは通信回線等が事故により停止した場合</li>
        <li>その他、当人が本サービスの提供が困難と判断した場合</li>
      </ol>
    </li>
    <li>当人は、本サービスの提供の停止または中断により、ユーザーまたは第三者が被ったいかなる不利益または損害についても、一切の責任を負わないものとします。</li>
  </ol>

  <h4 class="p-3">第7条（利用制限および登録抹消）</h4>
  <ol class="text-start">
    <li>当人は、ユーザーが以下のいずれかに該当する場合には、事前の通知なく、ユーザーに対して、本サービスの全部もしくは一部の利用を制限し、またはユーザーとしての登録を抹消することができるものとします。
      <ol class="text-start py-2">
        <li>本規約のいずれかの条項に違反した場合</li>
        <li>登録事項に虚偽の事実があることが判明した場合</li>
        <li>当人からの連絡に対し、一定期間返答がない場合</li>
        <li>本サービスについて、最終の利用から一定期間利用がない場合</li>
        <li>その他、当人が本サービスの利用を適当でないと判断した場合</li>
      </ol>
    </li>
    <li>当人は、本条に基づき当人が行った行為によりユーザーに生じた損害について、一切の責任を負いません。</li>
  </ol>

  <h4 class="p-3">第8条（退会）</h4>
  <p class="text-start">ユーザーは、当人の定める退会手続により、本サービスから退会できるものとします。</p>

  <h4 class="p-3">第9条（保証の否認および免責事項）</h4>
  <ol class="text-start">
    <li>
      当人は、本サービスに事実上または法律上の瑕疵（安全性、信頼性、正確性、完全性、有効性、特定の目的への適合性、セキュリティなどに関する欠陥、エラーやバグ、権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。
    </li>
    <li>
      当人は、本サービスに起因してユーザーに生じたあらゆる損害について、当人の故意又は重過失による場合を除き、一切の責任を負いません。ただし、本サービスに関する当人とユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合、この免責規定は適用されません。
    </li>
    <li>
      前項ただし書に定める場合であっても、当人は、当人の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害のうち特別な事情から生じた損害（当人またはユーザーが損害発生につき予見し、または予見し得た場合を含みます。）について一切の責任を負いません。また、当人の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害の賠償は、ユーザーから当該損害が発生した月に受領した利用料の額を上限とします。
    </li>
    <li>当人は、本サービスに関して、ユーザーと他のユーザーまたは第三者との間において生じた取引、連絡または紛争等について一切責任を負いません。</li>
  </ol>

  <h4 class="p-3">第10条（サービス内容の変更等）</h4>
  <p class="text-start">当人は、ユーザーへの事前の告知をもって、本サービスの内容を変更、追加または廃止することがあり、ユーザーはこれを承諾するものとします。</p>

  <h4>第11条（利用規約の変更）</h4>
  <ol class="text-start">
    <li>当人は以下の場合には、ユーザーの個別の同意を要せず、本規約を変更することができるものとします。
      <ol class="text-start py-2">
        <li>本規約の変更がユーザーの一般の利益に適合するとき。</li>
        <li>本規約の変更が本サービス利用契約の目的に反せず、かつ、変更の必要性、変更後の内容の相当性その他の変更に係る事情に照らして合理的なものであるとき。</li>
      </ol>
    </li>
    <li class="text-start">当人はユーザーに対し、前項による本規約の変更にあたり、事前に、本規約を変更する旨及び変更後の本規約の内容並びにその効力発生時期を通知します。</li>
  </ol>

  <h4 class="p-3">第12条（個人情報の取扱い）</h4>
  <p class="text-start">当人は、本サービスの利用によって取得する個人情報については、当人「プライバシーポリシー」に従い適切に取り扱うものとします。</p>

  <h4>第13条（通知または連絡）</h4>
  <p class="text-start">
    ユーザーと当人との間の通知または連絡は、当人の定める方法によって行うものとします。当人は,ユーザーから,当人が別途定める方式に従った変更届け出がない限り,現在登録されている連絡先が有効なものとみなして当該連絡先へ通知または連絡を行い,これらは,発信時にユーザーへ到達したものとみなします。
  </p>

  <h4 class="p-3">第14条（権利義務の譲渡の禁止）</h4>
  <p class="text-start">ユーザーは、当人の書面による事前の承諾なく、利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し、または担保に供することはできません。</p>

  <h4 class="p-3">第15条（準拠法・裁判管轄）</h4>
  <ol class="text-start">
    <li>本規約の解釈にあたっては、日本法を準拠法とします。</li>
    <li>本サービスに関して紛争が生じた場合には、当人の本店所在地を管轄する裁判所を専属的合意管轄とします。</li>
  </ol>

  <p class="text-end">以上</p>


</div>