config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/stats', to: 'statistics#index'

  resources :items, only: %i[index show]
  resources :logs, only: %i[create destroy]
  # POST /logsの後のreloadを想定
  get '/logs', to: 'users#home'

  authenticated :user do
    root 'users#home', as: :authenticated_root
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  get '/users', to: 'users#registrations'
  get '/about', to: 'static_pages#about'
  get '/privacy_policy', to: 'static_pages#privacy'
  get '/terms_of_service', to: 'static_pages#service'
  root 'static_pages#home'
  post '/guest', to: 'users#guest'

  namespace :api do
    resources :items, only: %i[index update]
    namespace :stats do
      get 'all_lines'
      get 'all_pies'
      get 'accumulate_amounts'
    end
  end
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :item
  has_one :user, through: :item
  scope :order_desc, -> { order(created_at: :desc) }

  validates :item_id, presence: true
  validates :amount, numericality: { less_than_or_equal_to: 180, greater_than: 0 }
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :log_owner?, only: %i[destroy]
  before_action :set_items_includes_logs, only: %i[create]
  before_action :set_feed_logs, only: %i[create]

  def create
    @log = current_user.logs.build(log_params)
    if @log.save
      redirect_to authenticated_root_path, notice: '記録を保存しました。'
    else
      flash.now[:alert] = '1回の記録は0 ~ 180分にしてください'
      render 'users/home'
    end
  end

  # def edit
  # end

  # def update
  # end

  def destroy
    @log = current_user.logs.find(params[:id])
    @log.destroy
    redirect_to authenticated_root_path, notice: '記録を削除しました。'
  end

  private

  def log_params
    params.require(:log).permit(:amount, :item_id)
  end

  def log_owner?
    return if current_user == Log.find(params[:id]).user

    redirect_to root_path, alert: '権限のない操作です。'
  end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_log.html.erb
<div class="card mb-2">
  <ul class="list-group list-group-flush">
    <li class="list-group-item text-start w-25 border item-bg-<%= item_num(log.item)%>">
      <%= link_to log.item.name, item_path(log.item), class:"text-dark" %>
    </li>
    <li class="list-group-item">
      <%= log.amount %> min
  </ul>
    </li>
  <div class="card-footer text-end">
    <%= (log.created_at).strftime("%m月%e日 （%H:%M） ") %>
      <%= link_to "削除", log, method: :delete, class: "text-end", id: "delete-log-#{log.id}",  data: { confirm: '本当に削除しますか？' }  %>
  </div>
</div>