config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/stats', to: 'statistics#index'

  resources :items, only: %i[index show]
  resources :logs, only: %i[create destroy]
  # POST /logsの後のreloadを想定
  get '/logs', to: 'users#home'

  authenticated :user do
    root 'users#home', as: :authenticated_root
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  get '/users', to: 'users#registrations'
  get '/about', to: 'static_pages#about'
  get '/privacy_policy', to: 'static_pages#privacy'
  get '/terms_of_service', to: 'static_pages#service'
  root 'static_pages#home'
  post '/guest', to: 'users#guest'

  namespace :api do
    resources :items, only: %i[index update]
    namespace :stats do
      get 'all_lines'
      get 'all_pies'
      get 'accumulate_amounts'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :logs, dependent: :destroy

  validates :user, presence: true
  validates :name, length: { in: 0..15 }
  # groupdate gemによるグルーピングで干渉を避けつつ、取得する順番を固定する。
  # _log_formと、items#index主に使う。
  scope :get_fixed_order, -> { order(:id) }
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :item
  has_one :user, through: :item
  scope :order_desc, -> { order(created_at: :desc) }

  validates :item_id, presence: true
  validates :amount, numericality: { less_than_or_equal_to: 180, greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 30 }

  has_many :items, dependent: :destroy
  has_many :logs, through: :items, dependent: :destroy

  def set_twelve_items
    12.times do |i|
      items.create(name: "項目#{i + 1}")
    end
  end
end

app/controllers/api/charts_controller.rb
module Api
  class ChartsController < ApplicationController
    before_action :set_items_includes_logs, only: %i[all_pies all_lines]
    # FIXME: jsonデータを整形する。フロントで処理がすくなくなるように
    def all_lines
      render json: {
        content: @items.map do |item|
          {
            name: item.name,
            data: item.logs.group_by_month('logs.created_at', last: 3, format: '%m').sum('logs.amount / 60')
          }
        end,
        timeline: recent_3_months
      }
    end

    def all_pies
      render json: @items.map { |item|
        [item.name, item.logs.sum('amount / 60')]
      }
    end

    private

    def recent_3_months
      today = Time.zone.today
      [
        "#{today.prev_month(2).month}月",
        "#{today.prev_month.month}月",
        "#{today.month}月"
      ]
    end
  end
end

app/controllers/api/items_controller.rb
module Api
  class ItemsController < ApplicationController
    def index
      render json: current_user.items.get_fixed_order
    end

    def update
      item = Item.find(params[:id])
      if item.update(items_params)
        render json: '名前を更新しました。', status: :ok
      else
        render json: item.errors.full_messages, status: :unprocessable_entity
      end
    end

    private

    def items_params
      params.require(:item).permit(:name)
    end
  end
end

app/controllers/api/stats_controller.rb
module Api
  class StatsController < ApplicationController
    before_action :set_items_includes_logs, only: %i[all_pies all_lines accumulate_amounts]
    # FIXME: jsonデータを整形する。フロントで処理がすくなくなるように
    def all_lines
      render json: {
        content: @items.map do |item|
          {
            name: item.name,
            data: item.logs.group_by_month('logs.created_at', last: 3, format: '%m').sum('logs.amount / 60')
          }
        end,
        timeline: recent_3_months
      }
    end

    def all_pies
      render json: @items.map { |item|
        [item.name, item.logs.sum('amount / 60')]
      }
    end

    def accumulate_amounts
      render json: {
        total: @items.sum('logs.amount / 60'),
        monthly: @items.where('logs.created_at > ?', Time.zone.now.beginning_of_month).sum('amount / 60'),
        weekly: @items.where('logs.created_at > ?', Time.zone.now.beginning_of_week).sum('amount / 60')
      }
    end

    private

    def recent_3_months
      today = Time.zone.today
      [
        "#{today.prev_month(2).month}月",
        "#{today.prev_month.month}月",
        "#{today.month}月"
      ]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  # sign-up時にname属性の値を許可した。
  # account_editにもname属性を許可した。
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  private

  def set_items_includes_logs
    @items = current_user.items.get_fixed_order.includes(:logs)
  end

  def set_feed_logs
    @feed_logs = current_user.logs.order_desc.includes(:item).page(params[:page])
  end
end

app/controllers/item_controller.rb
class ItemController < ApplicationController
  #項目一覧画面
  def index
  end

  #項目名編集画面
  def edit
  end

  #項目名を更新する
  def update
  end

  

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_feed_logs, only: %i[show]
  # @itemsに代入
  before_action :set_items_includes_logs, only: %i[show]

  def index; end

  def show
    set_item
    item_owner?
    @feed_logs = @feed_logs.where(item_id: @item.id)
    # log_formのため
    @log = current_user.logs.build
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_owner?
    return if @item.user == current_user
    redirect_to root_path, alert: '権限のない操作です。'
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :log_owner?, only: %i[destroy]
  before_action :set_items_includes_logs, only: %i[create]
  before_action :set_feed_logs, only: %i[create]

  def create
    @log = current_user.logs.build(log_params)
    if @log.save
      redirect_to authenticated_root_path, notice: '記録を保存しました。'
    else
      flash.now[:alert] = '1回の記録は0 ~ 180分にしてください'
      render 'users/home'
    end
  end

  # def edit
  # end

  # def update
  # end

  def destroy
    @log = current_user.logs.find(params[:id])
    @log.destroy
    redirect_to authenticated_root_path, notice: '記録を削除しました。'
  end

  private

  def log_params
    params.require(:log).permit(:amount, :item_id)
  end

  def log_owner?
    return if current_user == Log.find(params[:id]).user

    redirect_to root_path, alert: '権限のない操作です。'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home; end

  def about; end

  def privacy; end

  def service; end
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  before_action :set_items_includes_logs, only: %i[index]

  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_feed_logs, only: %i[home]
  before_action :set_items_includes_logs, only: %i[home]
  skip_before_action :authenticate_user!, only: %i[guest]

  def home
    @log = current_user.logs.build
  end

  def guest
    user = User.find_by(email: 'guest@hogehoge.com')
    sign_in user
    redirect_to authenticated_root_path, notice: 'ゲストとしてログインしました。'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_helper.rb
module ItemHelper
  COLORS = %w[#D896AD #ECA2A3 #F1B996 #F6D699 #E3DE9A #A6D29A #93C7B7 #92BFC7 #90B0CA #B5A4C7 #B5A4C7 #C59DBB]

  # itemを引数に取り, userがもつ何個目(1..12)のitemであるかを返す。(1-based index)
  def item_num(item)
    user_items = item.user.items.get_fixed_order
    user_items.pluck(:id).find_index(item.id) + 1
  end

  def item_color(item)
    item_number = item_num(item)
    COLORS[item_number - 1]
  end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% if notice %>
    <p class="alert py-2 alert-success"><%= notice %></p>
<% elsif alert %>
    <p class="alert py-2 alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-secondary row text-white justify-content-between">
  <small class="col-md-4 p-2  text-center">Copy right&copy; 2022 Masanao Takahashi   All right Reserved</small>
  <div class="col-md-4 text-end p-2 pe-5">
    <%= link_to "利用規約", terms_of_service_path, class:"d-block text-white" %> 
    <%= link_to "プライバシーポリシー", privacy_policy_path, class:"d-block text-white" %> 
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm bg-secondary sticky-top">
  <div class="container-lg">
    <%= link_to "Recorda Me", root_path, class: "navbar-brand fs-3 fw-light" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav text-end">
        <li class="nav-item">
          <%= link_to "ホーム", root_path, class: "nav-link" %>
        </li> 
        <% if user_signed_in? %>
          <%= render "layouts/navbar_items/logged_in" %>
        <% else %>
          <%= render "layouts/navbar_items/non_login" %>
        <% end %>  
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecordaMe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
    <%= favicon_pack_tag 'media/images/favicon/apple-touch-icon.png' ,sizes: "180x180"%>
    <%= favicon_pack_tag 'media/images/favicon/favicon-32x32.png' ,sizes: "32x32"%>
    <%=  favicon_pack_tag 'media/images/favicon/favicon-16x16.png', sizes: "16x16"%>
    
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="py-5 text-center container min-vh-100">
      <%= render 'layouts/flash' %>
      <%= yield %>

      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/layouts/navbar_items/_logged_in.html.erb
<%# ログインしているnavbar_items_partial %>

<li class="nav-item">
  <%= link_to "統計", stats_path, class: "nav-link" %>
  </li>
<li class="nav-item">
  <%# ソーシャル機能のあしがかり%>
  <%# link_to "他のユーザをのぞく", "/users", class: "nav-link" %>
  </li>
<li class="nav-item dropdown">
  <a class="dropdown-toggle nav-link" href="#"
          role="button" id="dropdownMenuLink setting" data-bs-toggle="dropdown" aria-expanded="false">
          各種設定
  </a>
  <ul class="dropdown-menu dropdown-menu-end bg-secondary" aria-labelledby="dropdownMenuButton1">
    <li>
      <%= link_to "活動項目", items_path, class: "dropdown-item text-end text-black" %>
    </li>
    <li><hr class="dropdown-divider"></li>
    <li>
      <%= link_to "ユーザ情報", edit_user_registration_path, class: "dropdown-item text-end text-black"  %>
    </li>
  </ul>
</li>
<li class="nav-item">
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
</li>

app/views/layouts/navbar_items/_non_login.html.erb
<%# ログインしてないnavbar_items_partial %>
<li class="nav-item">
  <%= link_to "Recorda meとは", about_path, class: "nav-link" %>
</li>
<li class="nav-item">
  <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger mb-5 py-2">
    <ul class="fw-light mb-1">
        <% object.errors.full_messages.each do |message| %>
          <li style="list-style: none;"><%= message %></li>
        <% end %>
      </ul>
  </div>
<% end %>

app/views/shared/_log_form.html.erb
<section class="side-bar border p-2 mb-5 rounded-1 border-2">
  
    <h5 class="mb-3 pb-3 pt-2 border-bottom">今日の活動を記録しよう</h5>
  <div class="log_form container">
    <%= form_with(model: @log) do |form| %>
      <%= form.number_field :amount, in: 15..180, step: 15, class:"form-control d-inline w-50"%>
      <span class="ps-2">min</span>
      <div class="pe-2">
        <%= form.collection_select :item_id, @items, :id, :name, {} ,class: "form-select mt-3 w-50 ms-auto" %>
        <%= link_to "項目名を編集する" , items_path, class: "text-end d-block ms-auto", style: "width: 180px;"%>
      </div>
      <%= form.submit "記録する", class: "btn btn-secondary mt-3" %>
    <% end %>
  </div>
</section>